### ISSUE TITLE
Throws upon clicking on group names to fold/expand with RowGrouping plugin

### ISSUE THREAD

**Issue by r4j4h** [DataTables/KeyTable#11]
Gives `Uncaught TypeError: Cannot read property '1' of null ` . Appears to be from line 434 area, where the groups return false from _fnFindDtCell and it tries to grab an array indice from it.

Working on a slight fix to check before de-referencing the array which should solve the issue: https://github.com/DataTables/KeyTable/pull/12

**Comment by DataTables** [comment]
Massive delay in replying to this - sorry! The RowGrouping plug-in is 3rd party and not supported by myself. Indeed, I don't think it is even supported by the original author any more. Going to close this as it isn't something I'll be fixing.

**Comment by r4j4h** [comment]
Thank you for getting back to me on this =)
