### ISSUE TITLE
State Saving

### ISSUE THREAD

**Issue by nesl247** [DataTables/KeyTable#18]
It would be nice to be able to have the state of KeyTable saved like everything else. It would allow my users to be able to click a cell to mark it, and when they come back, it would still be marked.

**Comment by DataTables** [comment]
Finally, finally... :-) 1733f33bc91537d8b5a6bd94d46b8d56eef014ce . I'll be packing up v2 with revised documentation in the next week or two. Thanks for the suggestion.
