### ISSUE TITLE
Can't initialize

### ISSUE THREAD

**Issue by mgrigajtis** [DataTables/KeyTable#20]
Can't initialize a datatable:

```
this.keyTable = $.fn.dataTable.KeyTable(this.currentTable);
```

In the above code, this.currentTable is just a variable that contains a standard DataTable.  I get this error:
Uncaught TypeError: undefined is not a function dataTables.keyTable.js:1045

**Comment by DataTables** [comment]
You need to use the `new` keyword like in the examples: http://datatables.net/release-datatables/extensions/KeyTable/examples/simple.html

**Comment by mgrigajtis** [comment]
Same problem occurs with the new keyword.

On Thu, Feb 26, 2015 at 12:02 PM, Allan Jardine <notifications@github.com>
wrote:

> You need to use the new keyword like in the examples:
> http://datatables.net/release-datatables/extensions/KeyTable/examples/simple.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DataTables/KeyTable/issues/20#issuecomment-76218160>.
>



-- 
Matthew Grigajtis

**Comment by DataTables** [comment]
Can you link to a test page showing the issue. As you can see in the example I linked to about it should work.

**Comment by mgrigajtis** [comment]
No, it's an internal application.

**Comment by DataTables** [comment]
Can you use JSFiddle or similar to recreate the issue. Without being able to see the issue I can't resolve it. As I noted above, the link I provides shows that it should work.

**Comment by santigarcor** [comment]
I'm having the same problem my table has tabletools extension , no pagination, scrollX and scrollY.

**Comment by DataTables** [comment]
As requested above, please can you link to a test case so I can debug and help to resolve the issue.

**Comment by santigarcor** [comment]
There's the problem, it's a local application

**Comment by DataTables** [comment]
There isn't a huge amount of help I can offer without a way to recreate the issue. Could you use JSFiddle or http://live.datatables.net to recreate the problem please.

**Comment by khavrenko** [comment]
reproduced it with jQuery 2.1.3 (http://jsfiddle.net/dqhrceLm), for jQuery 1.11.0 extension works (http://jsfiddle.net/zL44mtun)

**Comment by DataTables** [comment]
Thank you! As a workaround you can pass in a jQuery object of the table element: http://jsfiddle.net/dqhrceLm/1/ .

I will ensure that this is addressed in the rewrite of KeyTable I'm going to be started soon (next week probably).

**Comment by reno1979** [comment]
Same problem here, also running jQuery 2.x and recent Datatable files (with plugins) 
The workaround works like a charm.

**Comment by DataTables** [comment]
This has been addressed now. With KeyTable 2 the preferred method of initialisation is to use the `keys` option in the DataTables' configuration object.
