### ISSUE TITLE
LastFocus throws exception

### ISSUE THREAD

**Issue by DusanSenior** [DataTables/KeyTable#23]
Hello,
using server side processing (but I think it is not neccessary) an execption is thrown when you try to move focus from last table row to next row at last page, but the last page contains less rows than current page. The problem occurs in dataTables.keyTables.js at

		if ( lastFocus ) {
			// Don't trigger a refocus on the same cell
			if ( lastFocus.node() === cell.node() ) {
				return;
			}

			// Otherwise blur the old focus
			this._blur();
		}
there lastFocus.node() function throws exception about anCells property of undefined object
Thanks for explanation/solution
Dusan

**Comment by DataTables** [comment]
Can you link to a page showing the issue please? [This example](http://datatables.net/extensions/keytable/examples/initialisation/server-side.html) appears to work okay.

**Comment by DusanSenior** [comment]
I have local project only, but you can use your example:
1) Go to page 5
2) Click at last row "New York" f.e.
3) press down key
4) page 6 is automatically loaded, but dataTable doesn't respond 

I have refreshed/cleared browser (Chrome, IE, FF) cache more times, doesn't help
Thank you

**Comment by DataTables** [comment]
Thanks for the clarification - I misunderstood before!

The error is actually in DataTables core and I've just [committed a fix](https://github.com/DataTables/DataTablesSrc/commit/6fe17f5956d8c318686798fbd797b2d092366005).

It is in the nightly now and will be in the 1.10.11 release.

**Comment by DusanSenior** [comment]
Thanks, great job!
Dusan
