### ISSUE TITLE
Lost focus

### ISSUE THREAD

**Issue by DusanSenior** [DataTables/KeyTable#24]
Hello,
dataTables loses focus when tries to move from last row to first row at next page (loaded from server).
The same situation is when you try to move from first row to last row of previous page.
I am using 
    jquery.dataTables.js
    dataTables.responsive.js
    Scripts/dataTables.bootstrap.js
Thanks for fix/explanation
Dusan

**Comment by DusanSenior** [comment]
I am stupid, there is blurable option...

**Comment by DataTables** [comment]
[`keys.blurable`](http://datatables.net/reference/option/keys.blurable) for anyone else who finds this :-).
