### ISSUE TITLE
Restoring state for focused element breaks if there are less rows

### ISSUE THREAD

**Issue by latagore** [DataTables/KeyTable#26]
We use DataTables for search results, so the number of table rows can vary from page to page. We have stateSave enabled for sorting preferences, but this also saves state for KeyTables. 

This means that if a user previously focuses on a cell in row 20 and there are less than 20 rows on the next search, then DataTables stops working entirely.

**Comment by latagore** [comment]
I resolved this on my end by adding the following to my DataTable options:
`"stateLoadParams": function (settings, data){
      // don't save focused cell
      data.keyTable = null;
    }`
However, I'm not sure this is the real solution. I don't think _focus() should stop DataTables from initializing because it's referring to a cell that doesn't exist.

**Comment by DataTables** [comment]
This was actually addressed by e307ba1ed6f0c4bd90a39d56e4e19338c6100df5. It will be included in the next release, which should be in the next day or two.
