### ISSUE TITLE
Focus moves up and down when scroll view is smaller than cell

### ISSUE THREAD

**Issue by latagore** [DataTables/KeyTable#27]
jsFiddle: https://jsfiddle.net/cj72ew2r/1/
When you use the arrow keys to move between cells and the cell is bigger than the viewport of the scrollable table, then the view scrolls to the top then to the bottom on each key press. It should at least stay at the top of each cell instead (although you still won't be able to see the entire cell anyways, with keys alone).

Related issue: _clicking_ on a cell should _never_ move the view. I think the normal expectation is that nothing should happen when you click on something other than a button. In addition, it makes it difficult to select text in unfocused cells that are not entirely in the viewport.

Steven

**Comment by DataTables** [comment]
Thanks for posting this. Great test case! I'll look into this as soon as possible and commit the fix.

**Comment by DataTables** [comment]
Also fixed the mouse click shift in a17fbb71927916ebfbab6d813d4fa826e11f8521. Thanks again for flagging these up!
