### ISSUE TITLE
Do not redraw DataTable when bPaginate is off

### ISSUE THREAD

**Issue by Rondom** [DataTables/KeyTable#3]
Inside _fnSetFocus KeyTable tries switches to the correct page when used with DataTables plugin. Since this code also triggers a redraw of the whole table it is quite slow.

I have disabled this code when bPaginate is off and could not notice any bad effect. I am not that into the codebase, so please have a second look to confirm.

**Comment by DataTables** [comment]
v2 will now only redraw the table when the cell to focus on is not visible on the current page. v2 is available in this repo - I'm about to stat writing the documentation for it and will be publishing later this month.
