### ISSUE TITLE
Version 2.30 throws undefined exception in dataTables.keyTable.js

### ISSUE THREAD

**Issue by hubertstrk** [DataTables/KeyTable#34]
We noticed after the upgrade to the 2.30 version that _dataTables.keyTable.js_ throws an undefined exception. The issue we see is that the variable _editor_ in the constructor function is undefined. Function __editor_ later in the file also uses an _editor_ variable. However the variable is set to

`var editor = this.c.editor;`

This is not the case for the constructor function. The exception happens in line 230. Maybe someone can comment on this. In the meanwhile we use one of the previous versions.

**Comment by jellylamp** [comment]
I have experienced this bug today as well: 
![image](https://user-images.githubusercontent.com/10146513/29639893-63992c9a-882a-11e7-983c-27f70b4b13e4.png)

**Comment by DataTables** [comment]
Sorry about that - I am a muppet. It didn't show up in the demos since they use a global `editor` variable (for the rendering of information about the instance). Fixed and will be published shortly.

Thanks for letting me know about it.

**Comment by hubertstrk** [comment]
No worries. Glad we could help.
