### ISSUE TITLE
Escape key to blur not working

### ISSUE THREAD

**Issue by webExplorerGuru** [DataTables/KeyTable#39]
Hello,

I was having issues with using the escape key to blur. Looking into the source I was confused by the following:
https://github.com/DataTables/KeyTable/blob/ee8721549b3cb5e64c79e76a27e4f933183c2640/js/dataTables.keyTable.js#L844
 As far as I understand `this.s.blurable` will always be `undefined`. Instead, I think it should be `this.c.blurable` like it is everywhere else.

**Comment by DataTables** [comment]
Agreed! Thanks for pointing that out. [Fixed here](https://github.com/DataTables/KeyTable/commit/a00d43ab6b299ddc958ef63d8c2411cc1b47eb1b).
