### ISSUE TITLE
Feature: Add setting for min/max col/row for focus

### ISSUE THREAD

**Issue by Rondom** [DataTables/KeyTable#5]
Some tables have "header"-columns on the left or right. Focusing these cells is usually not intended.

Adding a minimum and maximum for the rows and columns that can be focused would be helpful to remedy this situation.

**Comment by DataTables** [comment]
v2 has this ability now through its `columns` initialisation option which provides the option to specify a `column-selector`. Example:

```js
		keys: {
			columns: ':not(:first-child)'
		},
```

v2 will be published in the next few weeks and is available in this repo already.
