### ISSUE TITLE
loose focus - optional

### ISSUE THREAD

**Issue by matzke** [DataTables/KeyTable#6]
Sometimes you don't want to loose focus, when the user clickes outside the table so make this optional ;-) I would commit the code myself, but I'm still using SVN ...

* put code in separate function

```javascript
  /*
   * Function: _fnLooseFocus
   * Purpose:  Loose table focus when click outside the table
   * Returns:  -
   */
  function _fnLooseFocus()
  {
    jQuery(document).click( function(e) {
      var nTarget = e.target;
      var bTableClick = false;
      while ( nTarget )
      {
        if ( nTarget == oInit.table )
        {
          bTableClick = true;
          break;
        }
        nTarget = nTarget.parentNode;
      }
      if ( !bTableClick )
      {
        _fnBlur();
      }
    } );
  }  
```
* in function _fnInit add

```javascript
    if ( typeof oInit.looseFocus == 'undefined' ) {
      oInit.looseFocus = true;
    }

    if ( oInit.looseFocus == true ) {
      _fnLooseFocus();
    }
```

**Comment by DataTables** [comment]
Wow - _way_ too long on this one. I've just rewritten KeyTable and it now has a `blurable` option which can be set to `false` to stop the table from loosing focus. I've still to write the documentation for v2 and publish it, but it will be out soon!
